# Generated by Django 4.0.4 on 2022-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='svyaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('message', models.CharField(max_length=300, verbose_name='Сообщение')),
            ],
        ),
    ]
