# Generated by Django 4.0.4 on 2022-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menu_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(upload_to='static/img/menu'),
        ),
    ]
