# Generated by Django 4.0.4 on 2022-06-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_menu_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
